development:
  adapter: postgresql
  encoding: unicode
  database: spreecommercedev
  pool: 5
  username: abraham
  password: atunga_1989

test:
  adapter: postgresql
  encoding: unicode
  database: spreecommercetest
  pool: 5
  username: abraham
  password: atunga_1989

production:
  adapter: postgresql
  encoding: unicode
  database: spreecommerceprod
  pool: 5
  username: abraham
  password: atunga_1989

