# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 243de0ee54ab151626b8f56b8eb09f8effa7cf6da7cdf477bb8214d4de095240bcbc905451ab376aba5c9f4b593ed35e6a00237b79e72fae5071495e26be1368

test:
  secret_key_base: 0febac4c833ea01e270acd84b7cc1de803535b38fbea4b304476ed136f68f9409bd045b568e8e86018813813621f8339cf55a1650b8ef9fc3b5738ca021c0cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
